### ISSUE TITLE
Suggestions: provide line number of tokens and reproduce order of comments

### ISSUE THREAD

**Issue by lapalme** [pyconll/pyconll#117]
I am using pyconll to add annotations to Universal Dependencies  file, so I need to reproduce "verbatim" the comments. Unfortunately, sentence.conll() does not respect the original order of the "comments", so when I use it it creates some spurious "diffs" between the original and the one I modified. But I managed to get around this problem, by outputting the comments and each of the token separately. It would have been much simpler is sentence.conll() did this job.

It would be useful to have to have access to the line number within the "file" or "string", in order to be able to give information about each token. Ideally this would also be saved also for the sentence or even the comments.

**Comment by matgrioni** [comment]
Hi,

I agree that the comments should be presented as in the output file. This should be pretty easy to address, I'll try to have a fix out this weekend. In fact, I'm a bit surprised it isn't already working like this since I thought dictionaries in python now started to implicitly keep their ordering, so I'll have to investigate as to why this isn't happening. Are you modifying the comments at all also?

Regarding line numbers, I actually had this in v0.1-v1.x (I forgot where I got rid of it exactly). I thought it'd be helpful too, but at the same time I had issues with it, since it polluted the data focused classes, and if you start adding sentences to a Conll object, then you would have some sentences with this info, some without, and of course if you were to write out the Conll object to a file, the line numbers would no longer be correct. While getting the info in was not an issue, I didn't like how it was handled after, and think it was just confusing. Did you have a specific use for this information in mind? I had figured that the sentence id would also be enough for any downstream use cases and be more generalizable.

**Comment by lapalme** [comment]
I had problems with comments starting by "# newpar id = " that came out non it in the original order
so I had to do this:
            ## we must do this because sentence.conll() changes the order of meta lines..
            ##  and thus this generate spurious diffs
            for (key,val) in sentence._meta.items():
                fOut.write("# %s = %s\n"%(key,val) if val!=None else "# %s"%key) # e.g. TODO
            for token in sentence:
                fOut.write(token.conll()+"\n")
            fOut.write("\n")
---
My use case for line numbers is that I want to detect possible problems between fields (a form that looks like a plural form (e.g. women) and has a feature "Number=Sing". I could tag them with the line number, so that the author can open the text editor at the given line. This could be "advertised" as the "original line number" which cannot be relied upon if new tokens or comments are added.

**Comment by lapalme** [comment]
Excuse for the strange "bold and big" characters  in my previous message, I should have previewed it before posting it

**Comment by matgrioni** [comment]
No worries, I am able to make it out :). Thanks for the extra detail on it, I'll go off of "newpar id" for looking for issues.

Regarding line numbers, thanks for providing me an example use case that you had in mind. I agree that the line number here would be useful, but at the same time it seems to be that it is only marginally better than outputting the sentence and token id for most uses (although I am now thinking about how some test sets may not have an id, which would be a situation where alternatives are more difficult).

I also prefer having the API be more compact and "dense" so to speak, avoiding optional data that are conditionally valid / has asterisks. This just tends to make life easiers for maintainers, code readers, and final users. This was the original reason behind why I removed it and one or two other features that had similar issues. I also prefer for the data classes (Token, Sentence, Conll) to be focused on data representation (although since this would only be one field, it is not as big a deal).

I am thinking that one way around this would be to have a version of pyconll.load_from_* provide the line numbers for the current sentence. This wouldn't provide the line of the token, but at least would provide the raw starting line numbers for the sentence, along with satisfying some of my points. Let me know if you think this approach would be helpful, or maybe it is to cumbersome at that point?

**Comment by lapalme** [comment]
Of course, this is already something but getting the precise line of a token from its id given the "start" of  the sentence is not really straightforward. 

First  what is the starting line of a sentence ? its first token or the first "comment line" after the previous empty line.
Then:
- The  number of "comment" lines varies from one sentence to the other. 
- There is also the problem with lines that start with two numbers such as "3-4" in the case of elision that "don't count" for determining the precise line number of a token.

But I leave it to you to decide and thanks for making this useful API available, this is really a detail.

**Comment by matgrioni** [comment]
I've created a PR to address the comment ordering. For some reason, I thought it was a good idea for the comments to be sorted before outputting ><. This should solve the primary issue. Thanks for bringing this issue up. Looking at the format documentation, there definitely needs to be better support for the ordering of the comments in pyconll, since "newpar" or "newdoc" may fit better at the top of a sentence's comments, but right now there is no way to specify this. I wanted to update this interface anyway since it was a bit awkward, and this is good motivation to do so.

I will try to get out a new release later today with these changes, assuming everything looks good for the PR build. I'll let you know the new version once I do.

Regarding line numbers, as you say the token line number would still be not directly provided. The resolution would only be at the sentence level, which while not perfect, would at least surface this type of information at some granularity. I don't really see an easy way to add this support aside from this, unfortunately, but I will look at other general parsing libraries and see how they handle it for future reference.

**Comment by matgrioni** [comment]
pyconll version 3.0.5 has been release to pypi and conda, and has the appropriate fix.

**Comment by lapalme** [comment]
Thanks for the fix, I installed it and realized that I was using version 2 of pyconll.

But with this new version, I have another problem with "empty nodes" whose id have a decimal within them, and for which, by definition, their head must be empty:  "Empty nodes must have non-empty ID and DEPS fields and empty fields (i.e. underscores) for HEAD and DEPREL, because they are only part of the enhanced dependency graph." (https://universaldependencies.org/format.html)

So when I call sentence.to_tree() I get
    'The current sentence is not fully defined as a tree and has a token with an empty head at 10.1'
So sentence.to_tree() should "ignore" those empty nodes.
Also a related suggestion, on an error message such as the above, it would be convenient to give also the sentence.id, and not only the token.id, and better yet the line number ;-)

**Comment by matgrioni** [comment]
Well, that's definitely an issue. I will correct that asap (which given holiday weekend in the us will be Monday evening).

I agree that the error message could be better in general for parsing in pyconll during initial construction. I think this is important enough that I will add it to the next feature release. However for sentence parsing to a tree, I'm not really sure how the line number would make sense here (although sentence id would make sense). As I was alluding to before, a user could set a tokens dependency to None or empty (along with any other arbitrary set of transformations) and so the error message on calling to_tree would be confusing as it would reference a line number whose content is different than the current token and quite possibly not the reason for the error message. However, loading with the pyconll.load* methods should definitely include this info.

**Comment by matgrioni** [comment]
This issue should now be fixed in version 3.1.0. Thanks for your patience and for helping to make pyconll a better library!

Please let me know if there are any other issues you run into. I will create a separate issue to track adding line numbers to error messages and close this one. I will at least improve the parsing error messages since that proves more problematic than I would like even when I am debugging issues.
