### ISSUE TITLE
pyconll.exception.ParseError: The number of columns per token line must be 10. Invalid token: 3

### ISSUE THREAD

**Issue by ranjita-naik** [pyconll/pyconll#129]
I'm parsing the input as shown below. 

```
input="Parent information\nTeacher/Staff information\nDocumented progress"

nlp_stanza = init_parser("stanza",
                        "en",
                        parser_opts={
                        "use_gpu": True, "verbose": False},
                        is_tokenized=False,
                        include_headers=True)

parsed_doc = nlp_stanza(input)
conll = parsed_doc._.conll_str
conll_obj = load_from_string(conll)

```
Below is the content of conll 
```
# sent_id = 1
# text = Parent information

1       Parent  parent  NOUN    NN      Number=sing     2       compound        _       _
2       information     information     NOUN    NN      Number=sing     0       root    _       SpaceAfter=No
3

        SPACE   _SP     _       2               _       SpaceAfter=No

# sent_id = 2
# text = Teacher/Staff information

1       Teacher teacher NOUN    NN      Number=sing     4       compound        _       SpaceAfter=No   
2       /       /       PUNCT   ,       PunctType=comm  3       cc      _       SpaceAfter=No
3       Staff   staff   NOUN    NN      Number=sing     1       conj    _       _
4       information     information     NOUN    NN      Number=sing     0       root    _       SpaceAfter=No
5

        SPACE   _SP     _       4               _       SpaceAfter=No

# sent_id = 3
# text = Documented progress
1       Documented      document        VERB    VBN     VerbForm=part|Tense=past|Aspect=perf    2      amod     _       _
2       progress        progress        NOUN    NN      Number=sing     0       root    _       SpaceAfter=No

# sent_id = 4
# text = '
1       '       '       PUNCT   ``      PunctType=quot|PunctSide=ini    0       root    _       SpaceAfter=No
```

load_from_string is throwing the following error 
```
load_from_string(conll)
```
pyconll.exception.ParseError: The number of columns per token line must be 10. Invalid token: 3

Is there a way to disable the validation?

**Comment by matgrioni** [comment]
Hello,

The part after the colon in "Invalid Token: " is the line trying to be parsed. It looks like the first sentence with id 1, has the 3rd line ill-formed. It looks like stanza doesn't properly handle newlines or something of the sort. Both newlines in the original are being output as raw newlines. You may need to do more preprocessing on the string you input so that stanza can properly determine the sentence breaks.

A minimum approach may be to simply remove the \n from the input, although I haven't used stanza before so I cannot help too much there.

The rest of the input looks okay, but newlines are a pretty critical part of parsing conll. If they are malformed, it's not just cosmetic validation that is failing.

**Comment by matgrioni** [comment]
Closing this issue for now. If you need more help with this please let me know and re-open it.
