### ISSUE TITLE
installing Tree and SentenceTree with pip install?

### ISSUE THREAD

**Issue by francescomambrini** [pyconll/pyconll#33]
When installing via `pip install pyconll`, tree and sentencetree sub-modules are not installed (v. 1.1.0). Is this intended?

**Comment by matgrioni** [comment]
Thanks for bringing this to my attention. This is not intended, but it's a quick fix to just include the right source folders in `setup.py`. I'll have the fix in later today for this.

- Matias

**Comment by matgrioni** [comment]
This should now be taken care of in version 1.1.1 which should be installed by pip. Please let me know if this doesn't work for you.

**Comment by francescomambrini** [comment]
works perfectly! thanks for the very quick fix (and for the very nice library... ;-) )

**Comment by Henry-E** [comment]
Pip shows that pyconll version 1.1.2 is installed but `.tree` doesn't appear in the namespace?

![screenshot 2019-01-02 at 11 08 06](https://user-images.githubusercontent.com/12613144/50589489-c2e58280-0e7e-11e9-83c2-4a3f0d11292d.png)

**Comment by matgrioni** [comment]
I believe you have to make sure to do `import pyconll.tree`. If you simply do `import pyconll` several other items are automatically included, however the tree module is not one of them.

This is slightly confusing and is caused because on `import pyconll`, `pyconll.load` is automatically imported as well so that `load_from_file`, `load_from_string` etc are available. This brings other modules into scope however as well.

Let me know if adding the other import statement doesn't work for you.

**Comment by Henry-E** [comment]
Yep that works, thanks very much.

**Comment by matgrioni** [comment]
Yes definitely! That was an oversight on my part. It should be fixed now.

**Comment by matgrioni** [comment]
Thanks for the request. I think that this could be useful, but for now I'd rather focus any coding work on improving current features (such as parsing and sentence-comment handling), and I'd like to see if other people would find it useful as well. Feel free to open new issues for these as well.
