### ISSUE TITLE
Underscores in the text translate to None in token.form

### ISSUE THREAD

**Issue by matanster** [pyconll/pyconll#37]
This is a great library! 

It does what it says it does, and the source is clean and readable making class-level documentation superfluous. A small issue, perhaps by design or a compromise, is that an underscore as a conllu token form, translates to `None` in the value of `token.form`. 

An underscore is indeed the convention (or standard) for voidness/null-ness in UD field values, but it seems that an underscore as the token's form, in at least the [English EWT Treebank](https://github.com/UniversalDependencies/UD_English-EWT), really represents the token's form, not that the token's form or the token as a whole are in any sense not present or void. At least in that corpus's latest commit at the time of posting it seems to be the case, if taken as surface form not as formatting annotation. I wonder if this contradicts the semantics of an underscore as the token's form, in any other prominent treebank anyone has seen, if that's even allowed in the UD spec. Or whether its a simple bug without any known consequences of fixing.

Thanks in advance for sharing ...

@matanster

**Comment by matgrioni** [comment]
Thanks for using the library and the feedback!

The UD format specifies that `_` is used for an absent annotation and for the actual underscore character of course and that there is ambiguity between the two. I cannot say off the top of my head what the right approach should be in this case. There are few ways to disambiguate which one is right, and also the option of simply always providing the underscore as the character. I'm leaning toward always providing the underscore and changing the current behavior since I'd rather not have disambiguation logic in a library like this that is trying to be as transparent as possible.

If this is a blocking issue for you, I would recommend simply changing these instances to the underscore on the token, as this very well might be the eventual change I make.

I will get these changes into the next minor release, which should be coming soon.

**Comment by matgrioni** [comment]
After thinking a little bit there are 2 approaches I see:

* For token form and lemma simply take the text and do not do anymore processing regardless of underscore
* For token form and lemma take the text unless the token form exists and the lemma does not. In this case we can consider the lemma empty / `None`.

I find an issue with other disambiguation since it would either have to depend on the text metadata, which is not present on all UD versions and not enforced in CoNLL in general, or some rule based on the other fields which might not be intuitive.

**Comment by matanster** [comment]
I am adding two key people from the UD initiative to comment, @jnivre and @dan-zeman, hope they don't mind, as I think it would be good to get their perspective before changing anything one way or the other ....

**Comment by matanster** [comment]
If anything, maybe it should be a runtime option/flag, is this is an edge case (relating to only the `form` field), not precisely stipulated in any spec and various corpora have taken different approaches about it.

**Comment by jnivre** [comment]
Thanks for reaching out. Originally, underscores as null values were only permitted in certain fields, specifically LEMMA, XPOS, FEATS, MISC and DEPS, but not ID, FORM, UPOS, HEAD or DEPREL. This leads to ambiguity at least for the LEMMA field, assuming that the lemma of an underscore occurring in a sentence should also be an underscore, and I suppose this can only be disambiguated using context (for example, is the FORM also an underscore and are all other LEMMA values underscores), which is not ideal. The situation has been further complicated by the fact that some UD treebanks cannot release the underlying text, for copyright or license reasons, and therefore release annotations where all FORM values are underscores as well. In principle, I would not regard these as valid CONLL-U files, but rather as files that together with a script and the underlying text can be used to produce valid CONLL-U files. In practice, however, I guess these are just treated as any other CONLL-U files.

I am actually not sure what the current specs say about this. Maybe @dan-zeman is more up to date on this.

**Comment by matgrioni** [comment]
Thanks for the input Joakim! The legal / copyright scenario adds some complexity to this and the idea that these are not valid CoNLL-U files is definitely appealing. I cannot think of a reason for a FORM field to be null except for this situation. The UD documentation says that in the situations where there is ambiguity, handling is application dependent, so there is no central guidance on how to handle this.

Given this info, the simplest and most sensible disambiguation is that if only one of FORM or LEMMA is `_` then it is None. It would not make sense for FORM to actually be `_` but the LEMMA be something else, and vice-versa, for the LEMMA to be `_`, but for the FORM to not be.

@matanster How does this approach sound to you? I am not sure how frequently the `_` comes up in the English EWT treebank, and what it's occurrences look like, but I figure this will fix the issue overall.

**Comment by jnivre** [comment]
This sounds like a reasonable solution to me.

**Comment by matanster** [comment]
@jnivre thanks for chiming in, and sorry @matgrioni for my belated response. I think that when things get that complex, it is best to keep this kind of behavior as a runtime flag; done right this avoids future contradictory requests. If this approach makes sense, I can suggest how to implement/design this. 

This approach would mean that libraries (for CoNLL-U) would not make swaying assumptions about what to expect in the wild, and leave most disambiguation that the standard leaves open, vague, or not adopted by parts of the community, to the downstream user, while only implementing one or two built-in behaviors that would make sense in common scenarios. Rather than abstract over an underlying ambiguous reality of datasets.

@jnivre @matgrioni does this also make sense? 
what would be the maintenance downsides of such an approach for this library?

**Comment by matgrioni** [comment]
I think adding a runtime flag makes sense. In fact the current implementation does have a runtime flag but only on creating a Token, which a normal user would almost never do, so it isn't very helpful. I think this flag could be surfaced to the CoNLL loader module as an optional flag, to specify a different behavior.

I do intend to change the default behavior to my previous comment then. This interpretation handles most cases in a predictable way, and would handle the English EWT corpora properly.  I do not think it is to complex either, as it is at least what I would expect if only one of FORM or LEMMA was the `_`. The current flag currently specifies if underscores in LEMMA and FORM should be considered null or not. In this new approach, the flag would specify how to parse LEMMA and FORM if they are both `_`, either as `None` or `_`.

If you want to create a PR for this as well @matanster you are welcome to do so. Otherwise I will get to this in the second half of this month.

**Comment by matgrioni** [comment]
I have made a small change in version 1.1.4 for this fix, which should be available on pypi. I have not surfaced the options for how to parse `_` up to the load module level yet as I have some other improvements related to parsing for version 2.0 that this can go with.

Let me know if you have any other issues!
